In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
import numpy as np

In [12]:
a_33 = np.array([1,6,2,7,2,6,3,5])
print(a_33)
b_33 = np.array([6,4,2,5,7,3,8,9])
print(b_33)

[1 6 2 7 2 6 3 5]
[6 4 2 5 7 3 8 9]


In [11]:
c_33 = print(a_33 - b_33)
d_33 = print(b_33 + a_33)

[-5  2  0  2 -5  3 -5 -4]
[ 7 10  4 12  9  9 11 14]


In [13]:
a_33.shape

(8,)

In [15]:
np.matmul(a_33,b_33)

170

In [18]:
import numpy as np
a1_33 = np.zeros((2,2))
print(a1_33)

[[0. 0.]
 [0. 0.]]


In [19]:
b1_33 = np.ones((2,2))
print(b1_33)

[[1. 1.]
 [1. 1.]]


In [21]:
c1_33 = a1_33-b1_33
print(c1_33)

[[-1. -1.]
 [-1. -1.]]


In [25]:
d1_33 = np.identity(2)
print(d1_33)

[[1. 0.]
 [0. 1.]]


In [26]:
e1_33 = np.ones((4,8))
print(e1_33)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [27]:
d1_33 = np.zeros((8,8))
print(d1_33)
d1_33.shape

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


(8, 8)

In [ ]:
e1_33.ndim

2

In [ ]:
import numpy as np
r1_33 = np.random.rand(1,4)
print(r1_33)

[[0.85390378 0.59057795 0.54314428 0.34345499]]


In [ ]:
a3_33 = print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
a2_33 = np.zeros((4,4))+1
print(a2_33)
b2_33 = np.identity(4)
print(b2_33)
c2_33 = 4*b2_33
print(c2_33)
d2_33 = 3+c2_33
print(d2_33)
e2_33 = np.ones((3,3))
g2_33 = np.identity(3)*4
f2_33 = g2_33-e2_33
print(f2_33)
h2_33 = np.ones((3,3))*2
i2_33 =np.identity(3)
j2_33 = h2_33 + i2_33
print(j2_33)
k2_33 = f2_33/j2_33
n2_33 = k2_33*5
print(n2_33)
l2_33 = np.ones((3,3))
m2_33 = l2_33*-2.5  
print(m2_33)
o2_33 = n2_33-m2_33
print(o2_33)
p2_33 = np.identity(3)*7.5
q2_33 = o2_33 - p2_33
print(q2_33)
q2_33[0,0] = 1
q2_33[1,1] = 2
q2_33[2,2] = 3
print(q2_33)
r2_33 = q2_33*100
print(r2_33) 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[4. 0. 0. 0.]
 [0. 4. 0. 0.]
 [0. 0. 4. 0.]
 [0. 0. 0. 4.]]
[[7. 3. 3. 3.]
 [3. 7. 3. 3.]
 [3. 3. 7. 3.]
 [3. 3. 3. 7.]]
[[ 3. -1. -1.]
 [-1.  3. -1.]
 [-1. -1.  3.]]
[[3. 2. 2.]
 [2. 3. 2.]
 [2. 2. 3.]]
[[ 5.  -2.5 -2.5]
 [-2.5  5.  -2.5]
 [-2.5 -2.5  5. ]]
[[-2.5 -2.5 -2.5]
 [-2.5 -2.5 -2.5]
 [-2.5 -2.5 -2.5]]
[[7.5 0.  0. ]
 [0.  7.5 0. ]
 [0.  0.  7.5]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
[[100.   0.   0.]
 [  0. 200.   0.]
 [  0.   0. 300.]]
